version: '3.8'

services:
# 로컬에서 개발시 아래 내용 주석 !
#  app:
#    image: ${{ secrets.DOCKERHUB_USERNAME }}/view-app:latest
#    container_name: View
#    build:do
#      context: .
#      dockerfile: ./Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#      - redis
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
#      SPRING_DATASOURCE_USERNAME: ${DB_USER}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#      DB_HOST: mysql
#      DB_PORT: ${DB_PORT}
#      DB_NAME: ${DB_NAME}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
#    networks:
#      - app-network
#    volumes:
#      - ./app-data:/app-data

  db:
    restart: always
    image: mysql:8
    container_name: mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "${Redis_PORT}:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
  app-data:
